<project xmlns="http://maven.apache.org/POM/4.0.0">
	<properties>
		<lombok.version>1.18.30</lombok.version>
	</properties>

	<dependencies>
		<!-- Zariadenie 1: Verzia už je premenná -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
		</dependency>

		<!-- Zariadenie 2: Neobsahuje tag verzie (spravuje ho dependencyManagement) -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>
</project>