<project xmlns="http://maven.apache.org/POM/4.0.0">
  <properties>
    <java.version>25</java.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>3.2.1</version>
    </dependency>
  </dependencies>
</project>